// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubsidySystem.Models;

#nullable disable

namespace SubsidySystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubsidySystem.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id")
                        .HasComment("Уникальный идентификатор категории");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_name")
                        .HasComment("Наименование категории граждан");

                    b.Property<decimal?>("DiscountRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_rate")
                        .HasComment("Размер скидки на оплату ЖКУ в процентах");

                    b.Property<string>("EligibilityConditions")
                        .HasColumnType("text")
                        .HasColumnName("eligibility_conditions")
                        .HasComment("Описание условий предоставления льготы");

                    b.Property<string>("RegulatoryAct")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("regulatory_act")
                        .HasComment("Наименование документа, устанавливающего льготу");

                    b.HasKey("CategoryId")
                        .HasName("categories_pkey");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasComment("Категории граждан-льготников");
                        });
                });

            modelBuilder.Entity("SubsidySystem.Models.Citizen", b =>
                {
                    b.Property<int>("CitizenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("citizen_id")
                        .HasComment("Уникальный идентификатор гражданина");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CitizenId"));

                    b.Property<string>("ActualAddress")
                        .HasColumnType("text")
                        .HasColumnName("actual_address");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id")
                        .HasComment("Идентификатор категории льготности (внешний ключ)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("PassportIssueDate")
                        .HasColumnType("date")
                        .HasColumnName("passport_issue_date");

                    b.Property<string>("PassportIssuer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("passport_issuer");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("passport_number");

                    b.Property<string>("PassportSeries")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("passport_series");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("RegistrationAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_address");

                    b.Property<string>("Snils")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("snils")
                        .HasComment("Страховой номер индивидуального лицевого счета");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CitizenId")
                        .HasName("citizens_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "LastName", "FirstName" }, "idx_citizens_name");

                    b.HasIndex(new[] { "Snils" }, "idx_citizens_snils");

                    b.ToTable("citizens", null, t =>
                        {
                            t.HasComment("Персональные данные заявителей");
                        });
                });

            modelBuilder.Entity("SubsidySystem.Models.CompensationCalculation", b =>
                {
                    b.Property<int>("CompensationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("compensation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompensationId"));

                    b.Property<decimal>("ActualCharges")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_charges");

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("date")
                        .HasColumnName("calculation_date");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("CitizenId")
                        .HasColumnType("integer")
                        .HasColumnName("citizen_id");

                    b.Property<decimal>("CompensationAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("compensation_amount");

                    b.Property<decimal?>("ConsumptionRate")
                        .HasColumnType("numeric")
                        .HasColumnName("consumption_rate");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_rate");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("SocialNorm")
                        .HasColumnType("numeric")
                        .HasColumnName("social_norm");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("CompensationId")
                        .HasName("compensation_calculations_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CitizenId");

                    b.ToTable("compensation_calculations", null, t =>
                        {
                            t.HasComment("Результаты расчета компенсаций");
                        });
                });

            modelBuilder.Entity("SubsidySystem.Models.FamilyMember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberId"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<int>("CitizenId")
                        .HasColumnType("integer")
                        .HasColumnName("citizen_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool?>("IsStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_student")
                        .HasComment("Признак обучения (для учета иждивенцев)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("relationship")
                        .HasComment("Степень родства с заявителем");

                    b.Property<string>("Snils")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("snils");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MemberId")
                        .HasName("family_members_pkey");

                    b.HasIndex(new[] { "CitizenId" }, "idx_family_members_citizen");

                    b.ToTable("family_members", null, t =>
                        {
                            t.HasComment("Члены семьи заявителя");
                        });
                });

            modelBuilder.Entity("SubsidySystem.Models.Income", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("income_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncomeId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount")
                        .HasComment("Сумма дохода");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_name");

                    b.Property<int>("IncomeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("income_type_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end")
                        .HasComment("Окончание периода, за который получен доход");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start")
                        .HasComment("Начало периода, за который получен доход");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IncomeId")
                        .HasName("incomes_pkey");

                    b.HasIndex("IncomeTypeId");

                    b.HasIndex(new[] { "MemberId" }, "idx_incomes_member");

                    b.HasIndex(new[] { "PeriodStart", "PeriodEnd" }, "idx_incomes_period");

                    b.ToTable("incomes", null, t =>
                        {
                            t.HasComment("Сведения о доходах членов семьи");
                        });
                });

            modelBuilder.Entity("SubsidySystem.Models.IncomeType", b =>
                {
                    b.Property<int>("IncomeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("income_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncomeTypeId"));

                    b.Property<string>("IncomeTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("income_type_name");

                    b.Property<bool?>("IsConsidered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_considered")
                        .HasComment("Признак учета при расчете среднедушевого дохода");

                    b.HasKey("IncomeTypeId")
                        .HasName("income_types_pkey");

                    b.ToTable("income_types", null, t =>
                        {
                            t.HasComment("Классификатор видов доходов");
                        });
                });

            modelBuilder.Entity("SubsidySystem.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("CitizenId")
                        .HasColumnType("integer")
                        .HasColumnName("citizen_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("payment_amount");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentDetails")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_details");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_type")
                        .HasComment("Тип выплаты (субсидия, компенсация)");

                    b.Property<int>("RegistryId")
                        .HasColumnType("integer")
                        .HasColumnName("registry_id");

                    b.Property<int>("SourceCalculationId")
                        .HasColumnType("integer")
                        .HasColumnName("source_calculation_id")
                        .HasComment("Идентификатор исходного расчета");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'назначено'::character varying")
                        .HasComment("Статус выплаты (назначено, выплачено, отменено)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PaymentId")
                        .HasName("payments_pkey");

                    b.HasIndex("CitizenId");

                    b.HasIndex("RegistryId");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasComment("Детальные записи о выплатах");
                        });
                });

            modelBuilder.Entity("SubsidySystem.Models.PaymentRegistry", b =>
                {
                    b.Property<int>("RegistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("registry_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistryId"));

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("date")
                        .HasColumnName("approved_date");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("integer")
                        .HasColumnName("period_month");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer")
                        .HasColumnName("period_year");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_count");

                    b.Property<DateTime>("RegistryDate")
                        .HasColumnType("date")
                        .HasColumnName("registry_date");

                    b.Property<string>("RegistryNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("registry_number");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'формируется'::character varying")
                        .HasComment("Статус реестра (формируется, утвержден, отправлен)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.HasKey("RegistryId")
                        .HasName("payment_registries_pkey");

                    b.ToTable("payment_registries", null, t =>
                        {
                            t.HasComment("Реестры на перечисление выплат");
                        });
                });

            modelBuilder.Entity("SubsidySystem.Models.Standard", b =>
                {
                    b.Property<int>("StandardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("standard_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StandardId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("StandardType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("standard_type")
                        .HasComment("Тип норматива (ПМ, стандарт ЖКУ, доля расходов и т.д.)");

                    b.Property<decimal>("StandardValue")
                        .HasColumnType("numeric")
                        .HasColumnName("standard_value");

                    b.Property<string>("TerritoryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("territory_code")
                        .HasComment("Код территории применения норматива");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("StandardId")
                        .HasName("standards_pkey");

                    b.ToTable("standards", null, t =>
                        {
                            t.HasComment("Нормативные показатели для расчетов");
                        });
                });

            modelBuilder.Entity("SubsidySystem.Models.SubsidyCalculation", b =>
                {
                    b.Property<int>("CalculationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("calculation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalculationId"));

                    b.Property<decimal>("AveragePerCapitaIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("average_per_capita_income");

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("date")
                        .HasColumnName("calculation_date");

                    b.Property<int>("CitizenId")
                        .HasColumnType("integer")
                        .HasColumnName("citizen_id");

                    b.Property<decimal?>("CorrectionFactor")
                        .HasColumnType("numeric")
                        .HasColumnName("correction_factor");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("HousingStandard")
                        .HasColumnType("numeric")
                        .HasColumnName("housing_standard");

                    b.Property<decimal>("LivingWage")
                        .HasColumnType("numeric")
                        .HasColumnName("living_wage");

                    b.Property<decimal>("MaxAllowedShare")
                        .HasColumnType("numeric")
                        .HasColumnName("max_allowed_share");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasComment("Статус расчета (назначено, отказано, пересчитано)");

                    b.Property<decimal>("SubsidyAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("subsidy_amount");

                    b.Property<decimal>("TotalFamilyIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("total_family_income");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("CalculationId")
                        .HasName("subsidy_calculations_pkey");

                    b.HasIndex("CitizenId");

                    b.ToTable("subsidy_calculations", null, t =>
                        {
                            t.HasComment("Результаты расчета субсидий");
                        });
                });

            modelBuilder.Entity("SubsidySystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SubsidySystem.Models.UtilityCharge", b =>
                {
                    b.Property<int>("ChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("charge_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChargeId"));

                    b.Property<decimal>("ChargeAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("charge_amount");

                    b.Property<int>("CitizenId")
                        .HasColumnType("integer")
                        .HasColumnName("citizen_id");

                    b.Property<decimal?>("ConsumptionVolume")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("consumption_volume");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month")
                        .HasComment("Месяц начисления");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("service_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year")
                        .HasComment("Год начисления");

                    b.HasKey("ChargeId")
                        .HasName("utility_charges_pkey");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex(new[] { "CitizenId" }, "idx_utility_charges_citizen");

                    b.HasIndex(new[] { "Year", "Month" }, "idx_utility_charges_period");

                    b.HasIndex(new[] { "CitizenId", "ServiceTypeId", "Year", "Month" }, "idx_utility_charges_unique")
                        .IsUnique();

                    b.ToTable("utility_charges", null, t =>
                        {
                            t.HasComment("Фактические начисления за ЖКУ");
                        });
                });

            modelBuilder.Entity("SubsidySystem.Models.UtilityServiceType", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("service_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceTypeId"));

                    b.Property<string>("ServiceTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service_type_name");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unit_of_measure")
                        .HasComment("Единица измерения потребления");

                    b.HasKey("ServiceTypeId")
                        .HasName("utility_service_types_pkey");

                    b.ToTable("utility_service_types", null, t =>
                        {
                            t.HasComment("Классификатор услуг ЖКУ");
                        });
                });

            modelBuilder.Entity("SubsidySystem.Models.VCalculationSummary", b =>
                {
                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("CitizenId")
                        .HasColumnType("integer")
                        .HasColumnName("citizen_id");

                    b.Property<string>("CitizenName")
                        .HasColumnType("text")
                        .HasColumnName("citizen_name");

                    b.Property<int?>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.ToTable((string)null);

                    b.ToView("v_calculation_summary", (string)null);
                });

            modelBuilder.Entity("SubsidySystem.Models.VCitizenDetail", b =>
                {
                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<int?>("CitizenId")
                        .HasColumnType("integer")
                        .HasColumnName("citizen_id");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("RegistrationAddress")
                        .HasColumnType("text")
                        .HasColumnName("registration_address");

                    b.Property<string>("Snils")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("snils");

                    b.Property<string>("ЛьготнаяКатегория")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("льготная_категория");

                    b.Property<decimal?>("РазмерСкидки")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("размер_скидки");

                    b.ToTable((string)null);

                    b.ToView("v_citizen_details", (string)null);
                });

            modelBuilder.Entity("SubsidySystem.Models.Citizen", b =>
                {
                    b.HasOne("SubsidySystem.Models.Category", "Category")
                        .WithMany("Citizens")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("citizens_category_id_fkey");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SubsidySystem.Models.CompensationCalculation", b =>
                {
                    b.HasOne("SubsidySystem.Models.Category", "Category")
                        .WithMany("CompensationCalculations")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("compensation_calculations_category_id_fkey");

                    b.HasOne("SubsidySystem.Models.Citizen", "Citizen")
                        .WithMany("CompensationCalculations")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("compensation_calculations_citizen_id_fkey");

                    b.Navigation("Category");

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("SubsidySystem.Models.FamilyMember", b =>
                {
                    b.HasOne("SubsidySystem.Models.Citizen", "Citizen")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("family_members_citizen_id_fkey");

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("SubsidySystem.Models.Income", b =>
                {
                    b.HasOne("SubsidySystem.Models.IncomeType", "IncomeType")
                        .WithMany("Incomes")
                        .HasForeignKey("IncomeTypeId")
                        .IsRequired()
                        .HasConstraintName("incomes_income_type_id_fkey");

                    b.HasOne("SubsidySystem.Models.FamilyMember", "Member")
                        .WithMany("Incomes")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("incomes_member_id_fkey");

                    b.Navigation("IncomeType");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SubsidySystem.Models.Payment", b =>
                {
                    b.HasOne("SubsidySystem.Models.Citizen", "Citizen")
                        .WithMany("Payments")
                        .HasForeignKey("CitizenId")
                        .IsRequired()
                        .HasConstraintName("payments_citizen_id_fkey");

                    b.HasOne("SubsidySystem.Models.PaymentRegistry", "Registry")
                        .WithMany("Payments")
                        .HasForeignKey("RegistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("payments_registry_id_fkey");

                    b.Navigation("Citizen");

                    b.Navigation("Registry");
                });

            modelBuilder.Entity("SubsidySystem.Models.SubsidyCalculation", b =>
                {
                    b.HasOne("SubsidySystem.Models.Citizen", "Citizen")
                        .WithMany("SubsidyCalculations")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("subsidy_calculations_citizen_id_fkey");

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("SubsidySystem.Models.UtilityCharge", b =>
                {
                    b.HasOne("SubsidySystem.Models.Citizen", "Citizen")
                        .WithMany("UtilityCharges")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("utility_charges_citizen_id_fkey");

                    b.HasOne("SubsidySystem.Models.UtilityServiceType", "ServiceType")
                        .WithMany("UtilityCharges")
                        .HasForeignKey("ServiceTypeId")
                        .IsRequired()
                        .HasConstraintName("utility_charges_service_type_id_fkey");

                    b.Navigation("Citizen");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("SubsidySystem.Models.Category", b =>
                {
                    b.Navigation("Citizens");

                    b.Navigation("CompensationCalculations");
                });

            modelBuilder.Entity("SubsidySystem.Models.Citizen", b =>
                {
                    b.Navigation("CompensationCalculations");

                    b.Navigation("FamilyMembers");

                    b.Navigation("Payments");

                    b.Navigation("SubsidyCalculations");

                    b.Navigation("UtilityCharges");
                });

            modelBuilder.Entity("SubsidySystem.Models.FamilyMember", b =>
                {
                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("SubsidySystem.Models.IncomeType", b =>
                {
                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("SubsidySystem.Models.PaymentRegistry", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SubsidySystem.Models.UtilityServiceType", b =>
                {
                    b.Navigation("UtilityCharges");
                });
#pragma warning restore 612, 618
        }
    }
}
